/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Usuario
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Colectivo = new javax.swing.JLabel();
        BotEsperar = new javax.swing.JButton();
        BotSeguir = new javax.swing.JButton();
        BotDoblar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Noticiero = new javax.swing.JLabel();
        NoticieroCartel = new javax.swing.JLabel();
        RutaCompleta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Background.setFocusTraversalPolicyProvider(true);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Colectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/redimensionCole2.png"))); // NOI18N
        Background.add(Colectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 120, 30));

        BotEsperar.setBackground(new java.awt.Color(51, 255, 51));
        BotEsperar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BotEsperar.setForeground(new java.awt.Color(0, 0, 0));
        BotEsperar.setText("ESPERAR");
        BotEsperar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotEsperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotEsperarActionPerformed(evt);
            }
        });
        Background.add(BotEsperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 190, 60));

        BotSeguir.setBackground(new java.awt.Color(51, 255, 51));
        BotSeguir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BotSeguir.setForeground(new java.awt.Color(0, 0, 0));
        BotSeguir.setText("SEGUIR");
        BotSeguir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotSeguir.setMaximumSize(new java.awt.Dimension(118, 34));
        BotSeguir.setMinimumSize(new java.awt.Dimension(118, 34));
        BotSeguir.setPreferredSize(new java.awt.Dimension(118, 34));
        BotSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSeguirActionPerformed(evt);
            }
        });
        Background.add(BotSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 190, 60));

        BotDoblar.setBackground(new java.awt.Color(51, 255, 51));
        BotDoblar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BotDoblar.setForeground(new java.awt.Color(0, 0, 0));
        BotDoblar.setText("DOBLAR");
        BotDoblar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Background.add(BotDoblar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 600, 190, 60));

        Titulo.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Juego del Colectivo");
        Background.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 490, 70));

        Noticiero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/noticiero (2).jpg"))); // NOI18N
        Background.add(Noticiero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 410, 130));

        NoticieroCartel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        NoticieroCartel.setForeground(new java.awt.Color(51, 153, 255));
        NoticieroCartel.setText("Noticias: ");
        Background.add(NoticieroCartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 260, 30));

        RutaCompleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RutaDibujo.jpg"))); // NOI18N
        RutaCompleta.setText("jLabel1");
        Background.add(RutaCompleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 90, 1370, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotEsperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotEsperarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotEsperarActionPerformed

    private void BotSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSeguirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotSeguirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton BotDoblar;
    private javax.swing.JButton BotEsperar;
    private javax.swing.JButton BotSeguir;
    private javax.swing.JLabel Colectivo;
    private javax.swing.JLabel Noticiero;
    private javax.swing.JLabel NoticieroCartel;
    private javax.swing.JLabel RutaCompleta;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
