/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import TPO1.Chofer;
import TPO1.Colectivo;
import TPO1.Doblar;
import TPO1.Esperar;
import TPO1.Mapa;
import TPO1.OrganizadorSindicatos;
import TPO1.Piquteros;
import TPO1.Precargador;
import TPO1.Seguir;
import TPO1.Sindicato;
import TPO1.Ubicacion;
import java.awt.Container;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class Interfaz extends javax.swing.JFrame {

    private Colectivo colectivo;
    private Mapa mapa;
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setVisible(true);
    }
    
    public void iniciar(){
        Piquteros piqueteros = new Piquteros();
        
        int[][] plano = new int[7][26];

        Precargador.precargar(plano);
        
        this.mapa = new Mapa(plano);
        
//        Thread hilo = new Thread(){
//            public void run(){
//                while(true){
//                    mapa.mostrarMapa();
//                    try {
//                        Thread.sleep(1000);
//                    } catch (InterruptedException ex) {
//                        System.err.println("El colectivo pincho para siempre");
//                    }
//                    System.out.println("\n\n\n\n");
//                }
//            }
//        };
//        hilo.start();
        
        Ubicacion posInicial = new Ubicacion("Ruta 3", 3, 1);
        this.colectivo = new Colectivo(posInicial, mapa);
        
        OrganizadorSindicatos org = new OrganizadorSindicatos(piqueteros, mapa,this);
        
        int cantSind = 4;
        
        for(int i = 0; i < cantSind; i++){
            Sindicato sin = new Sindicato(org);
            sin.ejecutar();
        }

        fondo.add(colectivoLabel);
        
        Chofer chofer = new Chofer(colectivo, mapa, this);
        chofer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        colectivoLabel = new javax.swing.JLabel();
        BotEsperar = new javax.swing.JButton();
        BotSeguir = new javax.swing.JButton();
        BotDoblar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Noticiero = new javax.swing.JLabel();
        NoticieroCartel = new javax.swing.JLabel();
        informacionCartel = new javax.swing.JScrollPane();
        informacionTexto = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();
        RutaCompleta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Background.setFocusTraversalPolicyProvider(true);
        Background.setPreferredSize(new java.awt.Dimension(1300, 700));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        colectivoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ColectivoHorizontal.png"))); // NOI18N
        Background.add(colectivoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        BotEsperar.setBackground(new java.awt.Color(51, 153, 255));
        BotEsperar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BotEsperar.setForeground(new java.awt.Color(0, 0, 0));
        BotEsperar.setText("ESPERAR");
        BotEsperar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotEsperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotEsperarActionPerformed(evt);
            }
        });
        Background.add(BotEsperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 190, 60));

        BotSeguir.setBackground(new java.awt.Color(51, 153, 255));
        BotSeguir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BotSeguir.setForeground(new java.awt.Color(0, 0, 0));
        BotSeguir.setText("SEGUIR");
        BotSeguir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotSeguir.setMaximumSize(new java.awt.Dimension(118, 34));
        BotSeguir.setMinimumSize(new java.awt.Dimension(118, 34));
        BotSeguir.setPreferredSize(new java.awt.Dimension(118, 34));
        BotSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSeguirActionPerformed(evt);
            }
        });
        Background.add(BotSeguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 190, 60));

        BotDoblar.setBackground(new java.awt.Color(51, 153, 255));
        BotDoblar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BotDoblar.setForeground(new java.awt.Color(0, 0, 0));
        BotDoblar.setText("DOBLAR");
        BotDoblar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotDoblar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotDoblarActionPerformed(evt);
            }
        });
        Background.add(BotDoblar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 600, 190, 60));

        Titulo.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Simulacion Colectivo");
        Background.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, 70));

        Noticiero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/noticiero (2).jpg"))); // NOI18N
        Background.add(Noticiero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 410, 130));

        NoticieroCartel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        NoticieroCartel.setForeground(new java.awt.Color(51, 153, 255));
        NoticieroCartel.setText("Noticias: ");
        Background.add(NoticieroCartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 260, 30));

        informacionCartel.setBackground(new java.awt.Color(255, 255, 255));
        informacionCartel.setBorder(null);
        informacionCartel.setForeground(new java.awt.Color(255, 255, 255));
        informacionCartel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        informacionCartel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        informacionCartel.setAutoscrolls(true);
        informacionCartel.setFocusable(false);

        informacionTexto.setBackground(new java.awt.Color(255, 255, 255));
        informacionTexto.setColumns(20);
        informacionTexto.setFont(new java.awt.Font("Bitstream Charter", 1, 20)); // NOI18N
        informacionTexto.setForeground(new java.awt.Color(0, 0, 0));
        informacionTexto.setRows(5);
        informacionTexto.setBorder(null);
        informacionTexto.setFocusable(false);
        informacionCartel.setViewportView(informacionTexto);

        Background.add(informacionCartel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 380, 90));

        fondo.setMinimumSize(new java.awt.Dimension(1300, 700));
        fondo.setPreferredSize(new java.awt.Dimension(1300, 700));
        Background.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        RutaCompleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RutaDibujo.jpg"))); // NOI18N
        RutaCompleta.setText("jLabel1");
        RutaCompleta.setName(""); // NOI18N
        Background.add(RutaCompleta, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 90, 1370, 510));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotEsperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotEsperarActionPerformed
        colectivo.ejecutarEstrategia(new Esperar());
    }//GEN-LAST:event_BotEsperarActionPerformed

    private void BotSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSeguirActionPerformed
        colectivo.ejecutarEstrategia(new Seguir());
    }//GEN-LAST:event_BotSeguirActionPerformed

    private void BotDoblarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotDoblarActionPerformed
        colectivo.ejecutarEstrategia(new Doblar(mapa));
    }//GEN-LAST:event_BotDoblarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton BotDoblar;
    private javax.swing.JButton BotEsperar;
    private javax.swing.JButton BotSeguir;
    private javax.swing.JLabel Noticiero;
    private javax.swing.JLabel NoticieroCartel;
    private javax.swing.JLabel RutaCompleta;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel colectivoLabel;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane informacionCartel;
    private javax.swing.JTextArea informacionTexto;
    // End of variables declaration//GEN-END:variables

    /**
     * Desplaza al objeto grafico del colectivo
     * @param nuevaX -> Se corresponde con la columna de la matriz
     * @param nuevaY -> Se corresponde con la fila de la matriz
     */
    public void moverColectivo(int nuevaX, int nuevaY){
        int posX = colectivoLabel.getLocation().x;
        int posY = colectivoLabel.getLocation().y;
        int limY = (nuevaY-posY);
        if(limY > 0){
            //ROTAR
            colectivoLabel.setIcon(new ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Lab-trabajo1\\src\\Imagenes\\ColectivoAbajo.png"));
            colectivoLabel.setBounds(posX, posY, 30, 120);
            for(int i = 0; i < limY; i++){
                posY++;
                colectivoLabel.setLocation(posX, posY);
                try {
                    Thread.sleep(10);
                } catch (InterruptedException ex) {
                }
            }
        }
        else{
            colectivoLabel.setIcon(new ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Lab-trabajo1\\src\\Imagenes\\ColectivoHorizontal.png"));
            colectivoLabel.setBounds(posX, posY, 120, 30);
            for(int i = 0; i > limY; i--){
                posY--;
                colectivoLabel.setLocation(posX, posY);
                try {
                    Thread.sleep(10);
                } catch (InterruptedException ex) {
                }
            }
        }
        
        int limX = nuevaX-posX;
        for(int i = 0; i < limX; i++){
            posX++;
            colectivoLabel.setLocation(posX, posY);
            try {
                Thread.sleep(10);
            } catch (InterruptedException ex) {
            }
        }
    }


    public void informarANoticiero(String mensaje){
        informacionTexto.append(mensaje.concat("\n"));
        informacionTexto.setCaretPosition(informacionTexto.getDocument().getLength());
    }

    AtomicInteger cont = new AtomicInteger(0);
    public JLabel aparecerPiqueteros(int posX, int posY) {
        
        JLabel piquetero = new JLabel();
       
        fondo.add(piquetero);
        
        piquetero.setBounds(posX, posY, 100, 74);
        piquetero.setIcon(new ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Lab-trabajo1\\src\\Imagenes\\Piqueteros.png"));
        
       
        return piquetero;
    }

    public void sacarImagen(JLabel labelDelete) {
         labelDelete.setVisible(false);
        fondo.remove(labelDelete);
    }
}
